### ISSUE TITLE
Hey, I think some of the adjustments are not beneficial.

### ISSUE THREAD

**Issue by WeirdMidas** [iamlooper/dex2oat-optimizer#4]
Well, let's go step by step:

Some of the Dalvik adjustments that this module has made have actually shown results.

Specifically these ones:

dalvik.vm.check-dex-sum=false
dalvik.vm.verify-bytecode=false
dalvik.vm.minidebuginfo=false
dalvik.vm.dex2oat-minidebuginfo=false

The others are functional, such as checking the startup string. In ROMs that don't have them, they can be beneficial.

However, one of them, which is checkinij in newer versions of Android (like 15) gives a sinister bootloop when it reaches 58 seconds of use.

And in one of them, I had to reinstall the ROM.

I realized that this happened because current Androids have become super dependent on error checking.

Along with that, tweaks like allowing dalvik to use SWAP are good... if we were still in 2018 and most people used devices with 2-3gb of ram. Since most people use devices with 4gb, this tweak is not that useful and may even be unbeneficial if the individual's swap is misconfigured.

Along with that, tweaks that change the systemui compilation, I've noticed that they are not entirely beneficial. On some newer androids (like the 15 I'm using now) the systemui is fully compiled in everything, that is, even if it is compiled in the speed-profile, it would still be inferior to the standard everything that current androids apply.

Since I don't want to just point out errors and criticize, I'll also give suggestions on what to add based on what I tested and used: 

dalvik.vm.dexopt-flags=v=n,o=a,u=n,m=y 

dalvik.vm.stack-trace-file=none

 the second is to disable dalvik stack tracing, similar to minidebuginfo. 

The first is the famous ART compilation flags I had already configured it before, and used a default configuration: but, if it really didn't work nowadays, it wouldn't crash like it did, and so, I reconfigured it with better flags and got a speed boost in the startup and execution of applications (a little, extremely little, but noticeable, after all, current devices are not the same as the old ones that could benefit from these flags)

The configurations it applies are:
v=n — Does not apply full verification.
o=a — "everything" optimization for applications
u=n = avoids optimizing based on old devices (where they used architectures other than big.LITTLE like the current ones)
m=y — applies mimap registration, it's like a "back cache", where it goes back faster (almost without noticeable difference) to the previous page.

I said this because I really like you and your modules, but I've noticed that some of them don't have completely beneficial adjustments, and this one from Dalvik is one of them. Sorry for writing such a long text, it's just that I really wanted to make all the points clear, especially since I'm sending an "issue" to my favorite developer.

**Comment by iamlooper** [comment]
Thanks for the feedback sir!
