### ISSUE TITLE
Suggestions for Android Enhancer, MemeUi Enhancer and dex2oat optimizer (sorry for this being an issue)

### ISSUE THREAD

**Issue by WeirdMidas** [iamlooper/dex2oat-optimizer#5]
Hello, iamlooper, remember me? Well, I came to bring some suggestions (and possible discoveries) for your dalvik optimizer module (and also maybe for your other two that use the same gadget)

When I used your dalvik optimizer, I noticed that it was inferior to the default configuration of my cell phone.

So much so that this was one of my past issues.

So, I wanted to make a suggestion to optimize the packages in a "strategic and different way"

I'm still testing on my cell phone, and they proved to be better than the speed-profile compilation applied by the module.

And here are the "discoveries"

Build Prop:

dalvik.vm.image-dex2oat-filter=speed

dalvik.vm.dex2oat-filter=speed

these two were used in the app to optimize ZYGOTE and the system IMAGE.

I applied these two build props, and I got a SLIGHT improvement in responsiveness.

At the time I thought it was placebo, but I noticed that even my chatgpt opens faster, as well as my github too. And my apps have more tendency to "instantly launch" than before, which happened once in every 10 opens, and now happens once in every 7 opens.

Along with this, package optimization, unlike speed-profile, I found a more effective way than using this type of compilation, which is to apply speed and everything only to essential system services, as occurs here:

pm compile -m everything com.android.surfaceflinger
pm compile -m everything com.android.systemui
pm compile -m speed com.android.launcher3
pm compile -m speed com.android.inputmethod.latin
pm compile -m speed com.android.settings
pm compile -m speed com.android.wifi

I applied the speed profile to some, and everything to others that were more "important"

With this more "precise" adjustment, I got much faster even with low battery (as I am now).

Well, I just wanted to share my findings, maybe you already know them, but I wanted to give you my suggestion and my idea for your module. I wish you a good afternoon, good night and good morning in advance.

**Comment by iamlooper** [comment]
Thanks for the feedback! again
